--Create the ODS database
--CREATE DATABASE ODS ;

-- Create the DWH database
--CREATE DATABASE DWH ;


--Create the ODS TABLE
--Create the TRUNCATE TABLE


CREATE TABLE ODS.dbo.BNLC(
	ID_LIEU VARCHAR(MAX),
	ID_LOCAL VARCHAR(MAX),
	NOM_LIEU VARCHAR(MAX),
	AD_LIEU VARCHAR(MAX),
	COM_LIEU VARCHAR(MAX),
	INSEE VARCHAR(MAX),
	TYPE0 VARCHAR(MAX),
	DATE_MAJ VARCHAR(MAX),
	OUVERT VARCHAR(MAX),
	SOURCES VARCHAR(MAx),
	XLONG VARCHAR(MAX),
	YLAT VARCHAR(MAX),
	NBRE_PL VARCHAR(MAX),
	NBRE_PMR VARCHAR(MAX),
	DUREE VARCHAR(MAX),
	HORAIRES VARCHAR(MAX),
	PROPRIO VARCHAR(MAX),
	LUMIERE VARCHAR(MAX),
	COMM VARCHAR(MAX)
);

TRUNCATE TABLE ODS.dbo.BNLC ;

BULK INSERT ODS.dbo.BNLC
FROM 'C:\Users\bacar\Downloads\BNLC.csv'
WITH
(
	FIRSTROW=2
)